// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmvqaMy7dZVy1gQUpBZ3hWO_Orva660N8',
    appId: '1:491129677231:web:33f28fac930473d9147b5a',
    messagingSenderId: '491129677231',
    projectId: 'whatsapp-c151a',
    authDomain: 'whatsapp-c151a.firebaseapp.com',
    storageBucket: 'whatsapp-c151a.appspot.com',
    measurementId: 'G-GHTMJSD8SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcwi19U_ZM-__z0uRB0iHliCHgm58pegg',
    appId: '1:491129677231:android:e4b529240fc84f77147b5a',
    messagingSenderId: '491129677231',
    projectId: 'whatsapp-c151a',
    storageBucket: 'whatsapp-c151a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRwbl3JIc_o4_1ISJoNIu0nCm00A57ujE',
    appId: '1:491129677231:ios:8bd2078bb6cd24de147b5a',
    messagingSenderId: '491129677231',
    projectId: 'whatsapp-c151a',
    storageBucket: 'whatsapp-c151a.appspot.com',
    iosClientId: '491129677231-3ptt0hv5kcag6e9111jh6famtk1vd0gr.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRwbl3JIc_o4_1ISJoNIu0nCm00A57ujE',
    appId: '1:491129677231:ios:8bd2078bb6cd24de147b5a',
    messagingSenderId: '491129677231',
    projectId: 'whatsapp-c151a',
    storageBucket: 'whatsapp-c151a.appspot.com',
    iosClientId: '491129677231-3ptt0hv5kcag6e9111jh6famtk1vd0gr.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsApp',
  );
}
